; erelang x64 backend bootstrap (NASM syntax, win64)
; autogenerated from IR v0
; entry action: main

default rel
section .text
global main

main:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    xor eax, eax
    add rsp, 32
    pop rbp
    ret

; function main
erelang_fn_main:
    push rbp
    mov rbp, rsp
    ; TODO: lower IR ops to machine-level calling convention
    ; let age, 10
    ; let GRADING, "A"
    ; let math_score, 100.0
    ; let name, "Alex"
    ; let names, list_new("Alex", "Adam", "Bob")
    ; todo stmt-lowering-not-yet, N7erelang9ForInStmtE
    ; ret
    xor eax, eax
    pop rbp
    ret

