cmake_minimum_required(VERSION 3.20)
project(erelangApp LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE MinSizeRel CACHE STRING "" FORCE)
endif()
if(MINGW)
  add_compile_options(-Os -ffunction-sections -fdata-sections)
  add_link_options(-s -Wl,--gc-sections)
endif()
add_executable(app main.cpp)
add_library(erelang STATIC IMPORTED)
set_target_properties(erelang PROPERTIES IMPORTED_LOCATION "D:/Development/Game/Physics/build_fix/lib/Debug/liberelang.a")
target_include_directories(erelang INTERFACE "D:/Development/Game/Physics/include")
target_include_directories(app PRIVATE "D:/Development/Game/Physics/include")
target_link_libraries(app PRIVATE erelang advapi32 user32 gdi32 comctl32 rpcrt4 winhttp)
